def get_col_name_map(columns: str, pos: int = 0) -> dict:
    """Create dictionary with key the original column name and value the `pos` part of the column name.
        This is most useful with polars pivot table and Great Tables.

        Example: '{"2021","Server"}' will be mapped to '2021'.
        Such labels are generated by polars pivot.


    Args:
        columns: columns to create mapping for
        pos: extract the value at `pos` from the original column name

    Returns:
        dictionary with original col name and extracted value.
    """

    return {n: n[1:-1].split(",")[pos][1:-1] for n in columns if "{" in n}
